project:
  type: book

book:
  title: "r_workshop_2023"
  author: "Zaw Myo Tun"
  date: "3/28/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



