project:
  type: book

book:
  title: "An Introduction to Data Analysis with R"
  author: "Zaw Myo Tun"
  date: "3/28/2023"
  chapters:
    - index.qmd
    - dataset.qmd
    - intro.qmd
    # - dplyr.qmd
    # - quarto.qmd
    # - factors.qmd
    # - data_viz.qmd
    # - descriptive.qmd
    # - regress.qmd
    - resources.qmd

format:
  html:
    theme: cosmo


