# Download the data

We will manually download the example dataset from this [link](https://drive.google.com/file/d/105FSGAX3fjIS-rcCSsimi9tesj6n8-7-/view?usp=share_link). If you are expecting problems with the network, it may be better to download the data before the workshop and store it on your computer.

The example dataset is a simplified subset of the [Myanmar Demographic Health Survey (2014-2015).](https://dhsprogram.com/pubs/pdf/FR324/FR324.pdf) In this analysis, we are primarily interested in maternal tetanus vaccination. Thus, women who reported at least one birth in the last five years were included in the dataset.

Maternal tetanus vaccination was defined as newborns protected against neonatal tetanus. According to the [Myanmar National Guidelines for Antenatal Care](https://themimu.info/sites/themimu.info/files/documents/Ref_Doc_National_Guidelines_for_Antenatal_Care_for_Service_Providers_May2018.pdf), a newborn is protected against neonatal tetanus if the mother has received any of the following:

1\. Two injections of tetanus toxoid containing vaccine during the last pregnancy

2\. Two or more injections, the last one within three years of the last pregnancy

3\. Three or more injections, the last one within five years of the last pregnancy

4\. Four or more injections, the last one within 10 years of the last pregnancy

5\. Five or more injections at any time prior to the last pregnancy

|         |                                   |                                                                       |
|------|-------------------------|----------------------------------------|
| **No.** | **Variable name**                 | **Variable label**                                                    |
| 1       | caseid                            | ID number of mothers                                                  |
| 2       | age                               | Age in years                                                          |
| 3       | state_region                      | State or region of residence                                          |
| 4       | residence                         | Urban or rural residence                                              |
| 5       | birth_order_last_child            | Birth order of last pregnancy                                         |
| 6       | education                         | Highest education level of mothers                                    |
| 7       | employ                            | Mother's occupation                                                   |
| 8       | wealth                            | Quintiles of mother's wealth index (specific to urban or rural areas) |
| 9       | get_help_permission               | Getting medical help for self: getting permission to go               |
| 10      | person_decides_healthcare         | Person who usually decides on woman's healthcare                      |
| 11      | get_help_not_go_alone             | Getting medical help for self: not wanting to go alone                |
| 12      | get_help_money                    | Getting medical help for self: getting money needed for treatment     |
| 13      | get_help_distance_health_facility | Getting medical help for self: distance to health facility            |
| 14      | ancplace                          | Type of facility where women received antenatal care                  |
| 15      | tetanus_vacc                      | Maternal tetanus vaccination                                          |
